services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=Tearsofblood@9
      - POSTGRES_USER=srija
      - POSTGRES_DB=shelter
    volumes:
    - db_data:/var/lib/postgresql/db_data
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"
  etl:
    build: .
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - db
volumes:
  db_data:
